pipeline:

  docker:
    image: plugins/docker
    repo: chrisns/mqtt-iot-bridge
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    when:
      branch: master